# get http://localhost:6000/
###
# get http://localhost:6000/api
###
get http://localhost:6000/api/auth
###
get http://localhost:6000/api/volunteers
###
get http://localhost:6000/api/businesses
###
get http://localhost:6000/api/requests
###
get https://replate-food-reuse.herokuapp.com/api/requests
###
# get http://localhost:6000/